services:
  - type: web
    name: hunyuan-video-api
    env: docker
    # Ultra plan: 8 cores, 32GB RAM - $450/month
    plan: ultra
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: MODEL_BASE
        value: /opt/render/project/src/ckpts
      - key: SAVE_PATH
        value: /opt/render/project/src/results
      - key: MAX_WORKERS
        value: "2"
      - key: PYTHONUNBUFFERED
        value: "1"
      # CPU optimization
      - key: OMP_NUM_THREADS
        value: "8"
      - key: MKL_NUM_THREADS
        value: "8"
      - key: TORCH_NUM_THREADS
        value: "8"
      - key: CUDA_VISIBLE_DEVICES
        value: ""
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/ckpts
      sizeGB: 100
    healthCheckPath: /health
    autoDeploy: true
